# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
heading_anchors: true
# Aux links for the upper right navigation
aux_links:
  "Just the Docs on GitHub":
    - "//github.com/pmarsceill/just-the-docs"
# Main navigation
layout: default
title: Documentation
# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2020 Svalbard. Distributed by an <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\">MIT license.</a>"
